### ISSUE TITLE
Issue with package import 

### ISSUE THREAD

**Issue by laurapfaff201** [paquiteau/brainweb-dl#2]
Hi Pierre-Antoine, thank you for providing this nice brainweb extension! :)

I wanted to check out the fuzzy segmentation but I am struggling a bit with the import of the python package, as I am getting the following error:

``Traceback (most recent call last):
  File "D:\PycharmProjects\project\stuff.py", line 5, in <module>
    import brainweb_dl
  File "C:\User\Anaconda3\envs\ptenv2\lib\site-packages\brainweb_dl\__init__.py", line 2, in <module>
    from .mri import get_mri
  File "C:\User\Anaconda3\envs\ptenv2\lib\site-packages\brainweb_dl\mri.py", line 11, in <module>
    from ._brainweb import (
  File "C:\User\Anaconda3\envs\ptenv2\lib\site-packages\brainweb_dl\_brainweb.py", line 87, in <module>
    class BrainWebTissueMap(Enum):
  File "C:\User\Anaconda3\envs\ptenv2\lib\site-packages\brainweb_dl\_brainweb.py", line 88, in BrainWebTissueMap
    v1 = Path(str(files("brainweb_dl.data") / "brainweb1_tissues.csv"))
  File "C:\User\Anaconda3\envs\ptenv2\lib\importlib\resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "C:\User\Anaconda3\envs\ptenv2\lib\importlib\_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "C:\User\Anaconda3\envs\ptenv2\lib\importlib\_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "C:\User\Anaconda3\envs\ptenv2\lib\pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\User\Anaconda3\envs\ptenv2\lib\pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\User\Anaconda3\envs\ptenv2\lib\pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType``

Do you have any idea how to fix this?

**Comment by paquiteau** [comment]
Hi Laura, 

Indeed this look like a packaging problem (brainweb-dl ships with a table of values for each tissue type)

Which Python version are you using ? Also I see from the traceback that you are (probably) running conda to install the package (and I forgot to test for this...) what is your setup and which command did you run ? 

As an alternative you can try to install it in a regular venv to see if the issue persist.

**Comment by laurapfaff201** [comment]
Thanks for your quick response! Actually the problem was the path for v1 and v2 in class BrainWebTissueMap(Enum) in the _brainweb.py file, probably because I am using a windows machine. After adjusting the path it seems to work :)

**Comment by paquiteau** [comment]
Hum I thought to have done thing well by using Python Pathlib, maybe it would need some more tweaking... 
What changes did you apply? I would be happy to have support for both linux and windows.
